environment:
  PYTHON: C:\Python27
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%APPVEYOR_BUILD_FOLDER%;%PATH%
  - pip install pyinstaller
build_script:
  - python convert.py
  - pyinstaller -F convert.py
  - dir
  - dir dist
artifacts:
   - path: dist\*
