environment:
  PYTHON: C:\Python27
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%APPVEYOR_BUILD_FOLDER%;%PATH%
  - pip install pyinstaller
build_script:
  - python convert.py
  - pyinstaller -F convert.py
  - cd dist
  - 7z a convert.zip convert.exe
artifacts:
   - path: dist/convert.zip
deploy:
  provider: GitHub
  auth_token:
    secure: bkzyRyhHswuOGV4qmGWex3EkEiR2cF821jJNdznXdVj0Iv1opO0YrOLj/ZfNeZZI
  artifact: convert.zip
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
